services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sistema_notificacoes'
      - 'MYSQL_PASSWORD=mvsaude'
      - 'MYSQL_ROOT_PASSWORD=testemv'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
